In [2]:
pip install numpy

Requirement already satisfied: numpy in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np
arr=[1,2,3,4,5,6,7,8,9]
minimum=np.min(arr)
print(minimum)

1

In [6]:
maximum=np.max(arr)
print(maximum)

9

In [8]:
mean=np.mean(arr)
mean

5.0

In [10]:
minimum=np.min(arr)
minimum

1

In [12]:
import numpy as np
arr=[10,20,30,40,50]
minimum=np.min(arr)
minimum

10

In [16]:
import numpy as npy
arr=[1,5,10,15,20,25,30,35,40]
minimum=npy.min(arr)
minimum

1

In [18]:
mean=npy.mean(arr)
mean

20.11111111111111

In [20]:
pip install pandas

Requirement already satisfied: pandas in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: six>=1.5 in /Users/rajthakur/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import pandas as pd
data1=pd.read_csv("data.csv")
data1.shape

(10, 3)

In [24]:
data1.head()

   roll no.     name  marks
0         1      raj     99
1         2  rajveer     98
2         3   ankush     90
3         4    shyam     97
4         5   somesh     95

In [26]:
data1.head(10)

   roll no.     name  marks
0         1      raj     99
1         2  rajveer     98
2         3   ankush     90
3         4    shyam     97
4         5   somesh     95
5         6   mohsin     94
6         7     moiz     93
7         8     Zayn     94
8         9   zishan     91
9        10       om     90